export type { IconProps } from './icon-base'
export { IconSvg } from './icon-base'
export { IconAdd } from './icon-add'
export { IconArrowLeft } from './icon-arrow-left'
export { IconCall } from './icon-call'
export { IconChange } from './icon-change'
export { IconDelete } from './icon-delete'
export { IconFavourite } from './icon-favourite'
export { IconLightMode } from './icon-light-mode'
export { IconMore } from './icon-more'
export { IconMute } from './icon-mute'
export { IconSearch } from './icon-search'
export { IconSettings } from './icon-settings'
